toolbar:
  - undo redo | fontsizeselect fontselect | forecolor backcolor | bold italic underline | alignleft aligncenter alignright | bullist numlist outdent indent | table  | code codesample link uploadimage |
plugins:
  - link
  - lists
  - textcolor colorpicker
  - codesample code
  - table
  - preview fullscreen
  - searchreplace
  - uploadimage

codesample_languages: [
        {text: 'HTML/XML', value: 'markup'},
        {text: 'JavaScript', value: 'javascript'},
        {text: 'CSS', value: 'css'},
        {text: 'Ruby', value: 'ruby'}
]

font_formats: 'Tmon-monsori=Tmon-Monsori; Tmon-Tium=Tmon-Tium; BM-Dohyeon=BM-Dohyeon; BM-Hanna=BM-Hanna; BM-Jua=BM-Jua; BM-Yeonsung=BM-Yeonsung; YJ-Yache=YJ-Yache; Andale Mono=andale mono,times;Arial=arial,helvetica,sans-serif;Arial Black=arial black,avant garde;Book Antiqua=book antiqua,palatino;Comic Sans MS=comic sans ms,sans-serif;Courier New=courier new,courier;Georgia=georgia,palatino;Helvetica=helvetica;Impact=impact,chicago;Symbol=symbol;Tahoma=tahoma,arial,helvetica,sans-serif;Terminal=terminal,monaco;Times New Roman=times new roman,times;Trebuchet MS=trebuchet ms,geneva;Verdana=verdana,geneva;Webdings=webdings;Wingdings=wingdings,zapf dingbats'
fontsize_formats: '8pt 10pt 12pt 14pt 15pt 18pt 24pt 36pt'