toolbar:
  - undo redo | fontsizeselect fontselect | forecolor backcolor | bold italic underline | alignleft aligncenter alignright | bullist numlist outdent indent | table  | code codesample link uploadimage |
plugins:
  - link
  - lists
  - textcolor colorpicker
  - codesample code
  - table
  - preview fullscreen
  - searchreplace
  - uploadimage

codesample_languages: [
        {text: 'HTML/XML', value: 'markup'},
        {text: 'JavaScript', value: 'javascript'},
        {text: 'CSS', value: 'css'},
        {text: 'Ruby', value: 'ruby'}
]

#font_formats: 'Tmon-monsori=Tmon-Monsori; Tmon-Tium=Tmon-Tium;'
fontsize_formats: '8pt 10pt 12pt 14pt 15pt 18pt 24pt 36pt'