toolbar:
  - undo redo | fontsizeselect fontselect | forecolor backcolor | bold italic underline | alignleft aligncenter alignright | bullist numlist outdent indent | table  | codesample link uploadimage |
plugins:
  - link
  - lists
  - textcolor colorpicker
  - codesample
  - table
  - preview fullscreen
  - searchreplace
  - uploadimage

codesample_languages: [
        {text: 'HTML/XML', value: 'markup'},
        {text: 'JavaScript', value: 'javascript'},
        {text: 'CSS', value: 'css'},
        {text: 'Ruby', value: 'ruby'}
]